MODES = [
    {
        "name": "Нормальный",
        "obstacle_speed": 12,
        "gravity": 1.8,
        "jump_force": -36,
        "jump_hold": -0.6,
        "bonus_chance": 0.15,
        "spawn_interval": (70, 140),
        "high_prob": 0.5,
    },
    {
        "name": "Быстрый",
        "obstacle_speed": 16,
        "gravity": 1.5,
        "jump_force": -36,
        "jump_hold": -0.6,
        "bonus_chance": 0.25,
        "spawn_interval": (70, 140),
        "high_prob": 0.5,
    },
    {
        "name": "Уклонение",
        "obstacle_speed": 7,
        "gravity": 1.8,
        "jump_force": -36,
        "jump_hold": -0.6,
        "bonus_chance": 0.15,
        "spawn_interval": (55, 110),
        "high_prob": 0.0,
    },
    {
        "name": "Психоделика",
        "obstacle_speed": 10,
        "gravity": 1.8,
        "jump_force": -36,
        "jump_hold": -0.6,
        "bonus_chance": 0.35,
        "spawn_interval": (40, 90),
        "high_prob": 0.3,
    },
]
